### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by acgkiss** [xunlu129/teriteri-backend#24]
[3]
2024-11-16 13:50:50.624  WARN 13832 --- [           main] org.elasticsearch.client.RestClient      : request [POST http://192.168.5.15:9200/user/_bulk] returned 1 warnings: [299 Elasticsearch-7.17.16-2b23fa076334f8d4651aeebe458a955a2ae23218 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
[ERROR] Tests run: 15, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 46.729 s <<< FAILURE! - in com.teriteri.backend.ApplicationTests
[ERROR] ossUploadImg  Time elapsed: 9.098 s  <<< ERROR!
java.io.FileNotFoundException: http:\127.0.0.1 (文件名、目录名或卷标语法不正确。)
	at com.teriteri.backend.ApplicationTests.ossUploadImg(BackendApplicationTests.java:117)

[ERROR] createIndex  Time elapsed: 1.838 s  <<< ERROR!
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [video/yWYaWa-7RFu6sdNDFtbkCw] already exists
	at com.teriteri.backend.ApplicationTests.createIndex(BackendApplicationTests.java:151)

[ERROR] deleteDoc  Time elapsed: 0.155 s  <<< ERROR!
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/delete] failed: [index_not_found_exception] no such index [test2]
	at com.teriteri.backend.ApplicationTests.deleteDoc(BackendApplicationTests.java:200)

[ERROR] updateDocUser  Time elapsed: 0.183 s  <<< ERROR!
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/update] failed: [document_missing_exception] [_doc][13]: document missing
	at com.teriteri.backend.ApplicationTests.updateDocUser(BackendApplicationTests.java:194)

[ERROR] bulkAddDocUser  Time elapsed: 0.423 s  <<< ERROR!
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/bulk] failed: [parse_exception] request body is required
	at com.teriteri.backend.ApplicationTests.bulkAddDocUser(BackendApplicationTests.java:185)

[INFO] Running com.teriteri.backend.comment.TestComment
2024-11-16 13:50:50.641  INFO 13832 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Neither @ContextConfiguration nor @ContextHierarchy found for test class [com.teriteri.backend.comment.TestComment], using SpringBootContextLoader
2024-11-16 13:50:50.642  INFO 13832 --- [           main] o.s.t.c.support.AbstractContextLoader    : Could not detect default resource locations for test class [com.teriteri.backend.comment.TestComment]: no resource found for suffixes {-context.xml, Context.groovy}.
2024-11-16 13:50:50.643  INFO 13832 --- [           main] t.c.s.AnnotationConfigContextLoaderUtils : Could not detect default configuration classes for test class [com.teriteri.backend.comment.TestComment]: TestComment does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
2024-11-16 13:50:50.684  INFO 13832 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration com.teriteri.backend.BackendApplication for test class com.teriteri.backend.comment.TestComment
2024-11-16 13:50:50.744  INFO 13832 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
2024-11-16 13:50:50.749  INFO 13832 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@320fc4b0, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@10724a72, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@25435731, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@10301d6f, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@5cd6719d, org.springframework.test.context.support.DirtiesContextTestExecutionListener@5ef591af, org.springframework.test.context.transaction.TransactionalTestExecutionListener@61b0af9f, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@71fb1da3, org.springframework.test.context.event.EventPublishingTestExecutionListener@1ecec098, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@6cc44207, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@8ecc457, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@21d3d6ec, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@49f1184e, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@7ebaf0d, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@694b1ddb]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s - in com.teriteri.backend.comment.TestComment
2024-11-16 13:50:51.702  INFO 13832 --- [ionShutdownHook] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
2024-11-16 13:50:51.725  INFO 13832 --- [ionShutdownHook] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ApplicationTests.bulkAddDocUser:185 » Elasticsearch [es/bulk] failed: [parse_e...
[ERROR]   ApplicationTests.createIndex:151 » Elasticsearch [es/indices.create] failed: [...
[ERROR]   ApplicationTests.deleteDoc:200 » Elasticsearch [es/delete] failed: [index_not_...
[ERROR]   ApplicationTests.ossUploadImg:117 » FileNotFound http:\127.0.0.1 (文件名、目录名或卷标语法...
[ERROR]   ApplicationTests.updateDocUser:194 » Elasticsearch [es/update] failed: [docume...
[INFO] 
[ERROR] Tests run: 16, Failures: 0, Errors: 5, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:11 min
[INFO] Finished at: 2024-11-16T13:50:55+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project backend: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\anime\Desktop\fsdownload\teriteri-backend\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

进程已结束，退出代码为 1

**Comment by xunlu129** [comment]
你elasticsearch设置密码没？application.yml的用户密码填了没？

**Comment by T-Y-F666** [comment]
问题

您好 这个问题如何解决呢：

2024-12-23 08:33:58.878 ERROR 22156 --- [nio-7070-exec-6] com.teriteri.backend.utils.ESUtil        : 查询ES相关视频文档时出错了：org.apache.http.ConnectionClosedException: Connection is closed

org.apache.http.ConnectionClosedException: Connection is closed
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:922)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:154)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.count(ElasticsearchClient.java:443)
	at com.teriteri.backend.utils.ESUtil.getUserCount(ESUtil.java:174)
	at com.teriteri.backend.service.impl.search.SearchServiceImpl.lambda$getCount$2(SearchServiceImpl.java:89)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	... 1 more
